In [1]:
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
np.shape(a)

(3,)

In [4]:
a[1]

2

In [ ]:
#Matrices

In [5]:
b = np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
             ])

In [6]:
b.shape

(3, 3)

In [7]:
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
d = np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
f = np.full((5, 2), 7)
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
g = b[1:, 1:] #Row_Start: Row_End, Column_Start:Column_End
g

array([[5, 6],
       [8, 9]])

In [12]:
g2 = b[0:2, 0:2]
g2

array([[1, 2],
       [4, 5]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
g

array([[5, 6],
       [8, 9]])

In [15]:
g[1,1]

9

In [16]:
g[1,1] = 2021
g

array([[   5,    6],
       [   8, 2021]])

In [17]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [18]:
b[1,1]

5

In [19]:
b[1,1] = 5050

In [20]:
g

array([[5050,    6],
       [   8, 2021]])

In [25]:
x = np.array([
    [1,2],
    [3,4]
],
dtype = np.float64)

y = np.array([
    [5,6],
    [7,8]
],
dtype = np.float64)
print('El matrix x es: \n',x )
print('El matrix y es: \n', y)

El matrix x es: 
 [[1. 2.]
 [3. 4.]]
El matrix y es: 
 [[5. 6.]
 [7. 8.]]


In [29]:
print('sum of matrix \n{} y \n{} is :\n {} '.format(x, y, x+y))

sum of matrix 
[[1. 2.]
 [3. 4.]] y 
[[5. 6.]
 [7. 8.]] is :
 [[ 6.  8.]
 [10. 12.]] 


In [30]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [31]:
np.sum(x, axis = 1) #axis 1 es rows

array([3., 7.])

In [32]:
x

array([[1., 2.],
       [3., 4.]])

In [33]:
np.sum(x, axis = 0) #axis 0 es columns

array([4., 6.])